[build]
target = "x86_64-unknown-none"
rustflags = ["-Cforce-frame-pointers=yes", "-Crelocation-model=pic"] 

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-none]
runner = [".cargo/runner.sh"]
# linker = "x86_64-elf-gcc"
# ar = "x86_64-elf-ar"
# rustflags = [
#     "-C", "link-args=-T.cargo/linker.ld -nostartfiles -nostdlib -nodefaultlibs -Wl,--gc-sections"
# ]
